# Importing our DataSet

In [22]:
import pandas as pd

data = pd.read_csv("BRCA.csv")

print(data)

       Patient_ID   Age  Gender  Protein1  Protein2  Protein3  Protein4  \
0    TCGA-D8-A1XD  36.0  FEMALE  0.080353   0.42638   0.54715  0.273680
1    TCGA-EW-A1OX  43.0  FEMALE -0.420320   0.57807   0.61447 -0.031505
2    TCGA-A8-A079  69.0  FEMALE  0.213980   1.31140  -0.32747 -0.234260
3    TCGA-D8-A1XR  56.0  FEMALE  0.345090  -0.21147  -0.19304  0.124270
4    TCGA-BH-A0BF  56.0  FEMALE  0.221550   1.90680   0.52045 -0.311990
..            ...   ...     ...       ...       ...       ...       ...
336           NaN   NaN     NaN       NaN       NaN       NaN       NaN
337           NaN   NaN     NaN       NaN       NaN       NaN       NaN
338           NaN   NaN     NaN       NaN       NaN       NaN       NaN
339           NaN   NaN     NaN       NaN       NaN       NaN       NaN
340           NaN   NaN     NaN       NaN       NaN       NaN       NaN

    Tumour_Stage                      Histology ER status PR status  \
0            III  Infiltrating Ductal Carcinoma  Positive  Positive
1             II             Mucinous Carcinoma  Positive  Positive
2            III  Infiltrating Ductal Carcinoma  Positive  Positive
3             II  Infiltrating Ductal Carcinoma  Positive  Positive
4             II  Infiltrating Ductal Carcinoma  Positive  Positive
..           ...                            ...       ...       ...
336          NaN                            NaN       NaN       NaN
337          NaN                            NaN       NaN       NaN
338          NaN                            NaN       NaN       NaN
339          NaN                            NaN       NaN       NaN
340          NaN                            NaN       NaN       NaN

    HER2 status                 Surgery_type Date_of_Surgery  \
0      Negative  Modified Radical Mastectomy       15-Jan-17
1      Negative                   Lumpectomy       26-Apr-17
2      Negative                        Other       08-Sep-17
3      Negative  Modified Radical Mastectomy       25-Jan-17
4      Negative                        Other       06-May-17
..          ...                          ...             ...
336         NaN                          NaN             NaN
337         NaN                          NaN             NaN
338         NaN                          NaN             NaN
339         NaN                          NaN             NaN
340         NaN                          NaN             NaN

    Date_of_Last_Visit Patient_Status
0            19-Jun-17          Alive
1            09-Nov-18           Dead
2            09-Jun-18          Alive
3            12-Jul-17          Alive
4            27-Jun-19           Dead
..                 ...            ...
336                NaN            NaN
337                NaN            NaN
338                NaN            NaN
339                NaN            NaN
340                NaN            NaN

[341 rows x 16 columns]

# Printing Certain Columns from Dataset

In [13]:
print(data[['Gender', 'Patient_Status']])

     Gender Patient_Status
0    FEMALE          Alive
1    FEMALE           Dead
2    FEMALE          Alive
3    FEMALE          Alive
4    FEMALE           Dead
..      ...            ...
336     NaN            NaN
337     NaN            NaN
338     NaN            NaN
339     NaN            NaN
340     NaN            NaN

[341 rows x 2 columns]

In [14]:
data.loc[data['Patient_Status']== "Dead"]

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.614470,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
4,TCGA-BH-A0BF,56.0,FEMALE,0.221550,1.90680,0.520450,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead
11,TCGA-BH-A0EA,72.0,FEMALE,-0.372700,0.55549,-0.667900,-0.350700,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Oct-17,13-Sep-18,Dead
18,TCGA-BH-A0DE,62.0,FEMALE,0.104640,0.70280,-0.298980,0.601030,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,16-Mar-17,20-Oct-19,Dead
25,TCGA-AC-A62Y,79.0,FEMALE,-0.036229,0.79551,-0.013525,1.629900,II,Mucinous Carcinoma,Positive,Positive,Positive,Modified Radical Mastectomy,17-Nov-17,11-Jan-18,Dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,TCGA-AN-A04A,36.0,FEMALE,0.231800,0.61804,-0.557790,-0.517350,III,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Simple Mastectomy,11-Nov-19,09-Feb-20,Dead
330,TCGA-A8-A085,44.0,MALE,0.732720,1.11170,-0.269520,-0.354920,II,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Other,01-Nov-19,04-Mar-20,Dead
331,TCGA-A1-A0SG,61.0,FEMALE,-0.719470,2.54850,-0.150240,0.339680,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,11-Nov-19,18-Jan-21,Dead
332,TCGA-A2-A0EU,79.0,FEMALE,0.479400,2.05590,-0.531360,-0.188480,I,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,21-Nov-19,19-Feb-21,Dead
333,TCGA-B6-A40B,76.0,FEMALE,-0.244270,0.92556,-0.418230,-0.067848,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,11-Nov-19,05-Jan-21,Dead

# Finding Stats from DataSet

In [15]:
data.describe()

              Age    Protein1    Protein2    Protein3    Protein4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean    58.886228   -0.029991    0.946896   -0.090204    0.009819
std     12.961212    0.563588    0.911637    0.585175    0.629055
min     29.000000   -2.340900   -0.978730   -1.627400   -2.025500
25%     49.000000   -0.358888    0.362173   -0.513748   -0.377090
50%     58.000000    0.006129    0.992805   -0.173180    0.041768
75%     68.000000    0.343598    1.627900    0.278353    0.425630
max     90.000000    1.593600    3.402200    2.193400    1.629900

In [16]:
data

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
2,TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive
3,TCGA-D8-A1XR,56.0,FEMALE,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56.0,FEMALE,0.221550,1.90680,0.52045,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
data.groupby(["Surgery_type"]).mean()

                                   Age  Protein1  Protein2  Protein3  Protein4
Surgery_type
Lumpectomy                   61.000000  0.153511  1.132050 -0.109783  0.129899
Modified Radical Mastectomy  57.041667 -0.040462  0.818256  0.008741  0.062784
Other                        59.400000 -0.128192  0.987188 -0.127066 -0.048148
Simple Mastectomy            58.641791 -0.041854  0.885682 -0.154920 -0.093512

In [56]:
data.groupby(["Age"]).mean()

      Protein1  Protein2  Protein3  Protein4
Age
29.0 -0.051933  0.915155 -0.650145  0.004020
32.0  0.125450  1.456500 -0.680300 -0.010378
35.0 -0.817530  1.790400 -1.041600  0.038522
36.0  0.260488  0.865673 -0.058627 -0.173220
37.0 -0.425900  1.161770  0.484005  0.327985
38.0 -0.203647  0.985847 -0.529990 -0.146820
39.0  0.067237  1.454833  0.006818 -0.528815
40.0 -0.061432  1.062767  0.097622 -0.419515
41.0  0.141737  0.421170  0.247938 -0.356048
42.0  0.145394  0.953034 -0.075080 -0.218543
43.0  0.210373  1.235657 -0.056117 -0.061262
44.0  0.509790  1.000168 -0.177728 -0.092082
45.0 -0.277902  0.955403 -0.335451 -0.258896
46.0 -0.000495  0.374139  0.100876  0.178256
47.0  0.063251  1.143840  0.020165  0.116816
48.0 -0.112784  0.426786  0.130507 -0.217015
49.0 -0.319147  0.645537 -0.063969 -0.144747
50.0  0.088831  1.163376 -0.177936  0.033803
51.0  0.014662  1.170812  0.122777 -0.437354
52.0  0.169288  1.677363 -0.300525  0.132026
53.0 -0.121979  1.199065 -0.199274 -0.014771
54.0 -0.138714  0.698332  0.385903  0.294652
55.0  0.017378  1.238575 -0.707448 -0.015405
56.0 -0.079058  0.829228 -0.251396  0.034986
57.0  0.086240  0.640582  0.421973  0.521427
58.0 -0.319067  0.796377 -0.286110  0.184212
59.0  0.173076  1.035072 -0.068882  0.040460
60.0  0.071511  1.174639 -0.087699  0.230342
61.0 -0.295188  1.398513 -0.432412 -0.030345
62.0  0.328807  1.051368 -0.198773 -0.128200
63.0 -0.051049  1.016037 -0.040893  0.131651
64.0 -0.084238  0.860698  0.097355 -0.221182
65.0 -0.180982  1.057928 -0.332924 -0.032400
66.0 -0.287639  1.170121  0.038117 -0.041000
67.0 -0.140854  0.331947 -0.128217  0.050833
68.0 -0.005581  0.944849 -0.050464 -0.022237
69.0 -0.183362  0.761088  0.209613 -0.027037
70.0  0.883845  0.985300 -0.441335  0.295865
71.0  0.115893  0.836234  0.067194  0.225096
72.0 -0.126130  0.715297 -0.354323  0.165531
73.0  0.044678  1.706497  0.015633 -0.182003
74.0  0.135478  1.073683 -0.305674  0.022569
75.0 -0.430283  0.701095 -0.151899  0.198637
76.0 -0.294037  0.095060  0.206279  0.548750
77.0 -0.073470  0.522819  0.065059 -0.002010
78.0 -0.438295  0.389307 -0.251425 -0.013643
79.0  0.101062  1.164623 -0.257724  0.285042
80.0  0.202236  1.253353 -0.412889  0.272972
81.0  0.823740  1.853100 -0.801870 -0.794130
82.0 -0.158570  0.527250 -0.085350 -0.219650
83.0 -1.268790  0.648120 -0.028275 -0.423915
84.0  0.168939  1.595000 -0.363599  0.442404
85.0  0.523165  0.714520 -0.132235  0.034895
87.0  0.310637  1.642100 -0.503295  0.415575
88.0 -0.913377  0.760100 -0.077807 -0.692513
89.0 -0.249780 -0.351330 -0.099624  0.758340
90.0 -1.388200  0.775040  0.290880 -0.924270

# Sorting Data

In [18]:
data.sort_values('Age')

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
129,TCGA-AO-A03M,29.0,FEMALE,-0.105680,0.93747,-0.62169,0.186370,I,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Simple Mastectomy,21-Mar-18,15-Mar-22,Dead
153,TCGA-C8-A273,29.0,FEMALE,0.001814,0.89284,-0.67860,-0.178330,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,09-Jun-18,15-Jun-18,Alive
130,TCGA-AN-A0FF,32.0,FEMALE,0.125450,1.45650,-0.68030,-0.010378,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,02-Nov-18,23-Apr-19,Dead
212,TCGA-A8-A07J,35.0,FEMALE,-0.817530,1.79040,-1.04160,0.038522,II,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Other,17-Oct-18,17-Oct-19,Alive
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Adding/Creating Columns

In [21]:
data['total protien'] = data['Protein1'] + data['Protein2'] + data['Protein3'] + data['Protein4']
data.head(4)

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status,total protien
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive,1.327563
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead,0.740715
2,TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive,0.963650
3,TCGA-D8-A1XR,56.0,FEMALE,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive,0.064850

# Filtering Data

In [37]:
data.loc[(data["ER status"] == "Positive") | (data["HER2 status"] == "Positive")]

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
2,TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive
3,TCGA-D8-A1XR,56.0,FEMALE,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56.0,FEMALE,0.221550,1.90680,0.52045,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,TCGA-AN-A04A,36.0,FEMALE,0.231800,0.61804,-0.55779,-0.517350,III,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Simple Mastectomy,11-Nov-19,09-Feb-20,Dead
330,TCGA-A8-A085,44.0,MALE,0.732720,1.11170,-0.26952,-0.354920,II,Infiltrating Lobular Carcinoma,Positive,Positive,Negative,Other,01-Nov-19,04-Mar-20,Dead
331,TCGA-A1-A0SG,61.0,FEMALE,-0.719470,2.54850,-0.15024,0.339680,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,11-Nov-19,18-Jan-21,Dead
332,TCGA-A2-A0EU,79.0,FEMALE,0.479400,2.05590,-0.53136,-0.188480,I,Infiltrating Ductal Carcinoma,Positive,Positive,Positive,Lumpectomy,21-Nov-19,19-Feb-21,Dead
333,TCGA-B6-A40B,76.0,FEMALE,-0.244270,0.92556,-0.41823,-0.067848,I,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Lumpectomy,11-Nov-19,05-Jan-21,Dead

In [42]:
data.loc[(data["Tumour_Stage"] == "II") & (data["Histology"] == "Mucinous Carcinoma") & (data["Age"] < 50)]

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
1,TCGA-EW-A1OX,43.0,FEMALE,-0.42032,0.57807,0.614470,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
16,TCGA-A2-A0D4,37.0,FEMALE,0.29490,1.36250,0.692380,0.410020,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,15-Jun-17,24-Oct-18,Alive
26,TCGA-A7-A5ZW,47.0,FEMALE,0.33186,-0.32765,0.003379,1.165800,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,27-Nov-17,10-Apr-18,Dead
239,TCGA-EW-A1P3,48.0,FEMALE,-0.34001,0.16257,-0.177200,0.412550,II,Mucinous Carcinoma,Positive,Positive,Negative,Simple Mastectomy,15-Jan-19,02-Dec-20,Alive

In [52]:
data.loc[data["Gender"] == "FEMALE", "Gender"] = "Woman"
data

,Patient_ID,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
0,TCGA-D8-A1XD,36.0,Woman,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,Alive
1,TCGA-EW-A1OX,43.0,Woman,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,Dead
2,TCGA-A8-A079,69.0,Woman,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,Alive
3,TCGA-D8-A1XR,56.0,Woman,0.345090,-0.21147,-0.19304,0.124270,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,Alive
4,TCGA-BH-A0BF,56.0,Woman,0.221550,1.90680,0.52045,-0.311990,II,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,Dead
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN